import streamlit as st
from audit_engine import audit_website
from ai_analyzer import generate_ai_judgment

st.set_page_config(
    page_title="AI Website Quality Auditor",
    page_icon="🔎",
    layout="wide",
)

st.title("🔎 AI-Assisted Website Quality Auditor")
st.caption("Week 2 — Lifestyle Websites | Automated facts + AI-generated judgment")

with st.sidebar:
    st.header("Website URLs")
    st.write("Enter 3–5 public/authorized Lifestyle website homepages.")
    urls_text = st.text_area(
        "One URL per line",
        placeholder="https://example.com\nhttps://example2.com\nhttps://example3.com",
        height=180,
    )
    run_audit = st.button("Run Website Audit", type="primary", use_container_width=True)

    st.divider()
    st.subheader("AI model")
    st.write("Set `GROQ_API_KEY` in your deployment secrets to enable AI scoring.")
    model_name = st.text_input("Model", value="openai/gpt-oss-120b")

if run_audit:
    raw_urls = [u.strip() for u in urls_text.splitlines() if u.strip()]
    urls = list(dict.fromkeys(raw_urls))

    if len(urls) < 3 or len(urls) > 5:
        st.error("Please provide between 3 and 5 unique URLs.")
        st.stop()

    results = []
    progress = st.progress(0)

    for i, url in enumerate(urls, start=1):
        with st.status(f"Auditing {url}", expanded=False):
            try:
                facts = audit_website(url)
                ai = generate_ai_judgment(facts, model_name=model_name)
                results.append({"facts": facts, "ai": ai})
            except Exception as exc:
                results.append({
                    "facts": {"url": url, "error": str(exc)},
                    "ai": None,
                })
        progress.progress(i / len(urls))

    st.success("Audit completed.")

    st.header("Audit Results")

    for item in results:
        facts = item["facts"]
        ai = item["ai"]
        st.divider()
        st.subheader(facts.get("url", "Unknown URL"))

        if facts.get("error"):
            st.error(f"Audit failed: {facts['error']}")
            continue

        c1, c2, c3 = st.columns(3)
        c1.metric("AI Score", f"{ai['score']}/100" if ai else "N/A")
        c2.metric("Internal Links Found", facts.get("internal_links_count", 0))
        c3.metric("Social Links", facts.get("social_links_count", 0))

        st.markdown("### Automatically Detected Facts")
        facts_display = {
            "HTTP status": facts.get("status_code"),
            "Pages/links found": facts.get("internal_links_count"),
            "Contact information": "Yes" if facts.get("has_contact_info") else "No",
            "Contact form": "Yes" if facts.get("has_contact_form") else "No",
            "Social links": facts.get("social_links_count"),
            "CTA buttons/links": facts.get("cta_count"),
            "Viewport meta tag": "Yes" if facts.get("has_viewport_meta") else "No",
            "Responsive CSS indicators": "Yes" if facts.get("responsive_css_indicators") else "No",
            "HTTPS": "Yes" if facts.get("https") else "No",
            "Title": facts.get("title") or "(missing)",
        }
        st.table(facts_display)

        if ai:
            st.markdown("### AI-Generated Judgment")
            st.info("The following score, problems, missing features, recommendations, and priority are generated by the configured AI model from the detected website signals.")

            st.write(f"**Score:** {ai['score']}/100")
            st.write(f"**Priority:** {ai['priority']}")

            col_a, col_b = st.columns(2)
            with col_a:
                st.write("**Problems**")
                for x in ai["problems"]:
                    st.write(f"- {x}")
                st.write("**Missing Features**")
                for x in ai["missing_features"]:
                    st.write(f"- {x}")
            with col_b:
                st.write("**Recommendations**")
                for x in ai["recommendations"]:
                    st.write(f"- {x}")
        else:
            st.warning("AI judgment was not generated. Add GROQ_API_KEY to deployment secrets.")

    st.divider()
    st.header("Methodology")
    st.write(
        "Python requests + BeautifulSoup perform deterministic website checks first. "
        "LangChain then sends only the collected factual signals and a short text summary "
        "to the AI model for judgment. This keeps automatically detected facts separate "
        "from AI-generated interpretation."
    )
else:
    st.info("Enter 3–5 authorized/public Lifestyle website URLs in the sidebar and click Run Website Audit.")
